# Generated by Django 4.0.6 on 2022-10-25 18:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_main_post_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fetured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
